record:
  target:
    entity:
      integration: ring_intercom_camera
      domain: camera
  fields:
    filename:
      required: true
      example: "/media/local/cameras/portal/video-clip.mp4"
      selector:
        text:
    duration:
      required: false
      default: 20
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
          mode: box
